### ISSUE TITLE
Remove the unused params for delete endpoints

### ISSUE THREAD

**Issue by MinervaMint** [Agile-Organization/recommendations#155]
**As a** user
**I need** correct and precise documentation of the APIs
**So that** I can understand and use them conveniently

**Assumptions:** 
* Swagger docs for a endpoint should not show duplicate or unused parameters

**Acceptance Criteria:**
```
Given the updated swagger docs
When I visit the docs
Then I should see correct documentation with no unused parameters for delete endpoints
```

**Comment by sushanthsamala** [comment]
@Mu-xsan The endpoints give a 500 error when strings are entered in place of product id and related product id, could you please create another story to resolve this?

**Comment by Mu-xsan** [comment]
Sorry, but which endpoint?

**Comment by sushanthsamala** [comment]
> Sorry, but which endpoint?

The endpoint that takes type id.

**Comment by sushanthsamala** [comment]
This happens when you use the UI

**Comment by Mu-xsan** [comment]
> This happens when you use the UI

OK, Got it

**Comment by Mu-xsan** [comment]
> This happens when you use the UI

Hi, I found that the error is 
[WARNING] [service] 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Since we don't have a URL /recommendations/<product_id:string>.

Could we modify the js to solve this but not return 400?
